# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27c346eab6ca30969869df69f6c39a59"
name = "Frontier Quote"
application_url = "https://app.frontierquote.com:8080"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes, write_draft_orders, read_draft_orders, write_app_proxy, read_products, read_orders, read_customers"

[auth]
redirect_urls = [ "https://app.frontierquote.com:8080/api/auth" ]

[app_proxy]
url = "/frontier-quote"
prefix = "apps"
subpath = "frontier-quote"

[build]
automatically_update_urls_on_dev = true
